#!/usr/bin/zsh

# lnch -- fuzzy launcher, directory switcher and file opener

if [ "$1" = "r" ]; then
  echo "$(print -rC1 -- $commands)" | fzf | xargs detach;
else
  file="$(find $HOME 2> /dev/null | fzf )"
    if [ -d "$file" ]; then
      cd "$file"
      pwd
      tree -L 1
    else
      rifle "$file"
    fi
fi

exit
